# Generated by Django 4.2.5 on 2023-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_whatsappcredentials_whatsappcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcredential',
            name='permanent_access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='whatsappcredential',
            name='phone_number_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappcredential',
            name='whatsapp_business_id',
            field=models.CharField(max_length=30),
        ),
    ]
