# Generated by Django 4.2.5 on 2023-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_whatsappcredential_permanent_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcredential',
            name='permanent_access_token',
            field=models.CharField(max_length=500),
        ),
    ]
