# Generated by Django 4.2.5 on 2023-11-13 09:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_parent_user_customuser_referral_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_string',
            field=models.CharField(default=api.models.generate_referral_string, max_length=8, unique=True),
        ),
    ]
