# Generated by Django 4.2.5 on 2023-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customuser_referral_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_distributor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
