# Generated by Django 4.2.5 on 2023-12-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(null=True, upload_to='company_logo'),
        ),
    ]
