# Generated by Django 4.2.5 on 2023-12-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_template_template_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('user', 'template_name')},
        ),
    ]
