# Generated by Django 4.2.5 on 2023-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_template_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_data', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
