# Generated by Django 4.2.5 on 2024-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledapicall',
            name='api_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledapicall',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
    ]
