# Generated by Django 4.2.5 on 2024-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_scheduledapicall_api_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='excel_feature',
            new_name='advanced_feature',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='messaging_feature',
            new_name='basic_feature',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='image_feature',
            new_name='standard_feature',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='personalised_feature',
        ),
    ]
