# Generated by Django 4.2.5 on 2024-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customuser_trial_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='trial_used',
            new_name='trial_user',
        ),
    ]
