# Generated by Django 4.2.5 on 2024-03-13 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('started_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plan_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
