# Generated by Django 4.2.5 on 2024-03-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_planpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='known_by',
            new_name='trial_plan',
        ),
    ]
