# Generated by Django 4.2.5 on 2024-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_whatsappcredential_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.FileField(null=True, upload_to='template_image'),
        ),
    ]
