# Generated by Django 4.2.5 on 2024-04-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_template_template_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, unique=True)),
                ('blog_content', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
